-- 独立效果编辑数据、字段历史、非法类型、失败回滚与保存回归。
WINDOW={w=1600,h=900}
require('src.utils.room')
require('src.utils.table')
require('src.utils.math')
require('src.objects.meta')
require('src.utils.beat')
dkjson=require('src.utils.dkjson')
easings=require('src.utils.easings')
require('src.utils.bezier')
log=function() end
local Chart=require('src.services.chartService')
local Event=require('src.models.Event')
local Note=require('src.models.Note')
fEvent=require('src.utils.event')
fEvent:init({chart=Chart,event=Event,coordinates=require('src.services.coordinateService')})
fNote={sort=function() Chart:sortNotes() end}
redo=require('plugins.redo')
local bus=require('src.utils.eventBus')
local notifications=0
bus:on('chart:mutated',function(change) if change.field=='effect' then notifications=notifications+1 end end)
Chart:setChart({note={{beat={1,0,1}}},event={{type='x',track=1,beat={0,0,1},beat2={9,0,1},from=30,to=50}},
    effect={},bpm_list={{beat={0,0,1},bpm=120,linear_ramp=0}}})
Chart:load()
local initialEvent=Chart:getChartEvent(1):toTable()
Chart:setEffectEditing(true)
assert(Chart:getEventCount()==0 and Chart:getChartEventCount()==1)
assert(Chart:add(Note.new({beat={3,0,1}}))==false)
for _, kind in ipairs({'scroll','jump','track_alpha','track_line_alpha','rotate'}) do
    local e=Event.new({type=kind,track=1,beat={2,0,1},beat2={4,0,1},from=1,to=2,
        trans={type='easings',easings=1,trans={0,0,1,1}}})
    assert(Chart:add(e))
end
assert(Chart:getEventCount()==5 and Chart:getEffectCount()==5)
local e=Chart:getEvent(1)
local old=e:getFrom()
e:setFrom(42)
assert(Chart:getEffect(1).from==42)
assert(redo:undo())
assert(Chart:getEffect(1).from==old)
assert(redo:redoOne())
assert(Chart:getEffect(1).from==42)
local before=dkjson.decode(Chart:encodeJson())
local ok=pcall(function()
    Chart:changeEffectFields(function()
        Chart:getEvent(1):setTo(123)
        Chart:getEvent(1):getTransData()[1]=0.3
        error('synthetic rollback')
    end)
end)
assert(not ok)
assert(table.eq(dkjson.decode(Chart:encodeJson()).effect,before.effect))
e=Chart:getEvent(1)
assert(Chart:delete(e))
assert(Chart:getEffectCount()==4)
assert(redo:undo() and Chart:getEffectCount()==5)
Chart:setEffectEditing(false)
assert(Chart:getEventCount()==1 and table.eq(Chart:getEvent(1):toTable(),initialEvent))
local saved=dkjson.decode(Chart:encodeJson())
assert(#saved.effect==5 and #saved.note==1 and #saved.event==1)
assert(saved.effect[1]._data==nil and saved.effect[1].track==1)
assert(notifications>0)
print('PASS: effect editor isolation, five types, undo/redo, delete, rollback, save and mutation notifications')

-- 服务完全脱离全局侧栏；实际界面适配器仍保持效果选择。
sidebar=setmetatable({}, {__index=function() error('服务不可读取侧栏') end})
Chart:setEffectEditing(true)
local selected=Chart:getEvent(1)
local panel={displayed_content='event',incoming={1},to=function(self,name) self.displayed_content=name end}
require('src.objects.sidebar.chart_notifications')(panel,Chart,bus)
selected:setBeat({20,0,1})
assert(Chart:getEvent(panel.incoming[1])==selected and panel.incoming[1]==5)
Chart:setEffectEditing(false)
assert(Chart:putEventGroup('独立',{event={}}))
Chart:setEffectEditing(true)
assert(Chart:beginEventGroupEdit('独立'))
assert(panel.displayed_content=='nil' and not Chart:isEditingEffect())
Chart:setChart({})
assert(not Chart:isEditingEventGroup())
Chart:load()
print('PASS: 服务无侧栏依赖、效果排序选择、上下文退出及谱面替换')
